/* ======================================================
* Generated by AN 
* University of Bologna
* ======================================================-
*/
package it.unibo.android.SmartDeviceGEN;
public class ActionCode {
	public static final int waitDroneActionCode = 3;
}//ActionCode
