/* ======================================================
* Generated by AN 
* University of Bologna
* ======================================================-
*/
package it.unibo.android.SmartDeviceGEN;
	import android.os.Bundle;
	import android.content.Intent;
import it.unibo.android.smartDevice.DashboardActivity;
import it.unibo.android.smartDevice.R;
	 //Layout Packages
	import android.view.View;
import android.widget.*;
	
public abstract class DashboardActivitySupport extends BaseActivity{
	protected String inputValue  = "TODO";	//Data value associated to an action
	protected String outputValue = "TODO";	//Data value to be sent
	protected String MY_FILE_PATH = "/data/data/it.unibo.android.smartDevice/files/";	
	protected DashboardActivity dummyObj = null; //To stimulate the user to define a class
	protected boolean activatedByGui = false;
	//LifeCycle methods
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.dashboard_layout);
			
	        
	        
	        }//onCreate
	
	
	protected void onResume() {
		super.onResume();
		lookAtInput();
	}//onResume
	protected void onDestroy() {
		super.onDestroy();
	}//onDestroy
	//Actions
	//Interactions
	/*
	*	INPUT
	*/
		//Look at the activity input in order to decide what to do
		protected void lookAtInput() {
			Intent sourceIntent = getIntent();
			if(sourceIntent != null && sourceIntent.getAction() != null)
			analyseInput(sourceIntent);
		}
	
		//Check the nature of the activity input
		protected void analyseInput(Intent i) {
			if (i.getAction().contains("action.MAIN")) {
				activatedByGui = true;
				doJob();
			} else execAction(i);
		}
		
		public boolean isActivatedByGUI() {
			return activatedByGui;
		}
		
		//Perform some local job
		protected abstract void doJob();
		
		//Execute some action
		protected void execAction(Intent input) {
		try {
			//println("DashboardActivity execAction "+input.getAction()+" "+input.getData()+" "+input.getExtras()); //0
		} catch(Exception e) {}
		}	
}//DashboardActivitySupport
