/* ======================================================
* Generated by AN 
* University of Bologna
* ======================================================-
*/
package it.unibo.android.SmartDeviceGEN;
	import android.os.Bundle;
	import android.content.Intent;
import it.unibo.android.smartDevice.MainActivity;
import it.unibo.android.smartDevice.R;
	 //Layout Packages
	import android.view.View;
import android.widget.*;
	
public abstract class MainActivitySupport extends BaseActivity{
	protected String inputValue  = "TODO";	//Data value associated to an action
	protected String outputValue = "TODO";	//Data value to be sent
	protected String MY_FILE_PATH = "/data/data/it.unibo.android.smartDevice/files/";	
	protected MainActivity dummyObj = null; //To stimulate the user to define a class
	protected boolean activatedByGui = false;
	//LifeCycle methods
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main_layout);
			
	//btnWait OnClickListener registration
	final Button btnWait = (Button) findViewById(R.id.btnWait);
	btnWait.setOnClickListener(new View.OnClickListener() {
		public void onClick(View v) {
			// Perform action on click
			btnWait_OnClick(v);
		}
	});
	        
	        
	        }//onCreate
	@Override
	public void println(String msg) {
		if (output == null){ 
			output = (TextView) findViewById(R.id.output);
		}
		output.append(msg+"\n");
	}
	
	private void btnWait_OnClick(View v){
			//Local InterAction
				try {
				waitDrone("",myBundle);
				//execAction(new Intent("waitDrone"));
				} catch (Exception e) {
				e.printStackTrace();
				}	
				
	}
	
	protected void onResume() {
		super.onResume();
		lookAtInput();
	}//onResume
	protected void onDestroy() {
		super.onDestroy();
	}//onDestroy
	//Actions
	protected abstract void waitDrone(String inputValue,Bundle b) throws Exception;
	//Interactions
	/*
	*	INPUT
	*/
		//Look at the activity input in order to decide what to do
		protected void lookAtInput() {
			Intent sourceIntent = getIntent();
			if(sourceIntent != null && sourceIntent.getAction() != null)
			analyseInput(sourceIntent);
		}
	
		//Check the nature of the activity input
		protected void analyseInput(Intent i) {
			if (i.getAction().contains("action.MAIN")) {
				activatedByGui = true;
				doJob();
			} else execAction(i);
		}
		
		public boolean isActivatedByGUI() {
			return activatedByGui;
		}
		
		//Perform some local job
		protected abstract void doJob();
		
		//Execute some action
		protected void execAction(Intent input) {
		try {
			//println("MainActivity execAction "+input.getAction()+" "+input.getData()+" "+input.getExtras()); //1
			 if(input.getAction().endsWith("waitDrone")){
				String inputValue = input.getData().getLastPathSegment();
				waitDrone(inputValue,input.getExtras());
				}
		} catch(Exception e) {}
		}	
}//MainActivitySupport
